// <auto-generated />
namespace IE_Clinics.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class TriagemTerminada : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TriagemTerminada));
        
        string IMigrationMetadata.Id
        {
            get { return "201810202242132_TriagemTerminada"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
