// <auto-generated />
namespace IE_Clinics.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ModeloMedicoAdicionado : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ModeloMedicoAdicionado));
        
        string IMigrationMetadata.Id
        {
            get { return "201810181437502_ModeloMedicoAdicionado"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
